//! Append-only log of committed changes.
//!
//! The change log is the substrate's only history. Higher layers
//! (relationships, entities) derive their state from it. The log is the
//! "raw change log" memory layer in `docs/redesign.md` §3.5.
//! Use `trim_before_batch` to reclaim memory.
//!
//! ## Ordering invariant
//!
//! Changes are pushed in the order they commit, which the engine
//! guarantees is consistent with their causal partial order: if A is in
//! B's predecessor set, A is recorded earlier.
//!
//! ## ChangeId density invariant
//!
//! The engine assigns `ChangeId`s as a dense monotonically-increasing
//! sequence starting from 0 and appends each change immediately after
//! minting its id. As a result the log has no id gaps: the change at
//! index `i` always has `id = changes[0].id + i`. `get()` relies on
//! this to compute array indices in O(1). `trim_before_batch` shifts the
//! offset but preserves density.

use std::collections::VecDeque;

use graph_core::{
    BatchId, Change, ChangeId, ChangeSubject, InfluenceKindId, LocusId, RelationshipId, TrimSummary,
};
use rustc_hash::{FxHashMap, FxHashSet};

/// Append-only log with O(1) lookup by id and O(k) subject/batch-filtered iteration.
///
/// Three reverse indices are maintained on every `append` and `trim_before_batch`:
/// - `by_locus` / `by_relationship` — map each subject to the ordered list of
///   change ids that targeted it.
/// - `by_batch` — maps each `BatchId` to its change ids for O(k) batch queries.
/// - `summaries` — per-locus `TrimSummary` entries emitted by `trim_before_batch`
///   (E2). These persist after raw changes are discarded and allow long-range
///   causal queries to follow a "coarse trail" instead of hitting a dead end.
#[derive(Debug, Default, Clone)]
pub struct ChangeLog {
    changes: Vec<Change>,
    by_locus: FxHashMap<LocusId, Vec<ChangeId>>,
    by_relationship: FxHashMap<RelationshipId, Vec<ChangeId>>,
    by_batch: FxHashMap<BatchId, Vec<ChangeId>>,
    /// Coarse summaries generated by `trim_before_batch` (E2).
    summaries: FxHashMap<LocusId, Vec<TrimSummary>>,
    /// Maps each trimmed ChangeId → the LocusId it targeted (E2).
    /// Allows `causal_coarse_trail` to resolve trimmed predecessor IDs back to
    /// their locus so the right TrimSummary can be fetched.
    trimmed_id_to_locus: FxHashMap<ChangeId, LocusId>,
}

impl ChangeLog {
    pub fn new() -> Self {
        Self::default()
    }

    /// Append a committed change. Returns the change's id for ergonomic
    /// chaining.
    pub fn append(&mut self, change: Change) -> ChangeId {
        let id = change.id;
        match change.subject {
            ChangeSubject::Locus(locus_id) => {
                self.by_locus.entry(locus_id).or_default().push(id);
            }
            ChangeSubject::Relationship(rel_id) => {
                self.by_relationship.entry(rel_id).or_default().push(id);
            }
        }
        self.by_batch.entry(change.batch).or_default().push(id);
        self.changes.push(change);
        id
    }

    /// Pre-allocate capacity for `additional` more changes.
    ///
    /// Calling this before a batch of `append`s avoids repeated Vec
    /// reallocations when the number of incoming changes is known upfront.
    pub fn reserve(&mut self, additional: usize) {
        self.changes.reserve(additional);
    }

    /// Bulk-append multiple changes from the same batch in a single pass.
    ///
    /// All changes must share the same `batch` field — the engine guarantees
    /// this by calling once per batch loop iteration.  IDs must be dense and
    /// monotone (the ChangeId density invariant); the BUILD phase pre-assigns
    /// them before this is called.
    ///
    /// Reverse indices (`by_locus`, `by_relationship`, `by_batch`) are built
    /// with a grouping pass over `changes` rather than one HashMap operation
    /// per change.  For large fan-in batches with few unique destination loci
    /// this reduces index HashMap ops from O(3n) to O(n_unique_subjects + 1).
    pub fn extend_batch(&mut self, changes: Vec<Change>) {
        if changes.is_empty() {
            return;
        }
        let batch = changes[0].batch;

        // Pass 1: group by subject into local HashMaps (smaller → hotter cache).
        // IDs are dense and sequential, so all belong to the same batch entry.
        let mut locus_groups: FxHashMap<LocusId, Vec<ChangeId>> =
            FxHashMap::with_capacity_and_hasher(16, Default::default());
        let mut rel_groups: FxHashMap<RelationshipId, Vec<ChangeId>> =
            FxHashMap::with_capacity_and_hasher(4, Default::default());

        for change in &changes {
            match change.subject {
                ChangeSubject::Locus(id) => {
                    locus_groups.entry(id).or_default().push(change.id);
                }
                ChangeSubject::Relationship(id) => {
                    rel_groups.entry(id).or_default().push(change.id);
                }
            }
        }

        // Pass 2: update by_batch with a single entry lookup, pushing IDs
        // directly to avoid an intermediate allocation.
        {
            let batch_vec = self.by_batch.entry(batch).or_insert_with(Vec::new);
            batch_vec.reserve(changes.len());
            for change in &changes {
                batch_vec.push(change.id);
            }
        }

        // Merge grouped ids into the persistent reverse indices.
        for (locus_id, ids) in locus_groups {
            self.by_locus.entry(locus_id).or_default().extend(ids);
        }
        for (rel_id, ids) in rel_groups {
            self.by_relationship.entry(rel_id).or_default().extend(ids);
        }

        self.changes.extend(changes);
    }

    pub fn len(&self) -> usize {
        self.changes.len()
    }

    pub fn is_empty(&self) -> bool {
        self.changes.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = &Change> {
        self.changes.iter()
    }

    /// Look up a change by id in O(1).
    ///
    /// `ChangeId`s are assigned as a dense monotonically-increasing sequence
    /// and the log is append-only in causal order, so the id's position in
    /// the `Vec` is determined by subtracting the first entry's id (the
    /// offset shifts after `trim_before_batch`). Returns `None` for ids that
    /// were trimmed or not yet committed.
    pub fn get(&self, id: ChangeId) -> Option<&Change> {
        let offset = self.changes.first()?.id.0;
        let idx = id.0.checked_sub(offset)? as usize;
        let change = self.changes.get(idx)?;
        debug_assert_eq!(change.id, id, "ChangeId/Vec index invariant violated");
        Some(change)
    }

    /// Iterate the changes that committed in a given batch.
    /// O(k) where k is the number of changes in the batch.
    pub fn batch(&self, batch: BatchId) -> impl Iterator<Item = &Change> + '_ {
        self.by_batch
            .get(&batch)
            .into_iter()
            .flat_map(|ids| ids.iter())
            .filter_map(|&id| self.get(id))
    }

    /// All batch IDs that have at least one committed change, in ascending order.
    ///
    /// Useful for iterating the full commit history without knowing the exact
    /// batch range in advance. After `trim_before_batch`, only batches at or
    /// after the retain boundary are returned.
    pub fn committed_batch_ids(&self) -> Vec<BatchId> {
        let mut ids: Vec<BatchId> = self.by_batch.keys().copied().collect();
        ids.sort_unstable();
        ids
    }

    /// Iterate the changes whose subject is a given locus, newest first.
    /// Used by the locus program when assembling its incoming inbox.
    /// O(k) where k is the number of changes to this locus.
    pub fn changes_to_locus(&self, locus: LocusId) -> impl Iterator<Item = &Change> + '_ {
        self.by_locus
            .get(&locus)
            .into_iter()
            .flat_map(|ids| ids.iter().rev())
            .filter_map(|&id| self.get(id))
    }

    /// Iterate the changes whose subject is a given relationship, newest
    /// first. Analogous to `changes_to_locus`.
    /// O(k) where k is the number of changes to this relationship.
    pub fn changes_to_relationship(
        &self,
        rel: RelationshipId,
    ) -> impl Iterator<Item = &Change> + '_ {
        self.by_relationship
            .get(&rel)
            .into_iter()
            .flat_map(|ids| ids.iter().rev())
            .filter_map(|&id| self.get(id))
    }

    /// Iterate the direct predecessor changes of `id` in predecessor-list
    /// order. Yields nothing if `id` is not in the log or has no predecessors.
    pub fn predecessors(&self, id: ChangeId) -> impl Iterator<Item = &Change> {
        self.get(id)
            .into_iter()
            .flat_map(|c| &c.predecessors)
            .filter_map(|pid| self.get(*pid))
    }

    /// Walk the causal DAG backwards from `start` in BFS order, returning
    /// every ancestor change. Each ancestor appears at most once. `start`
    /// itself is not included.
    ///
    /// Traversal stops at any predecessor whose id is no longer in the log
    /// (e.g. trimmed by `trim_before_batch`) — those ancestors are simply
    /// absent from the result.
    pub fn causal_ancestors(&self, start: ChangeId) -> Vec<&Change> {
        let Some(root) = self.get(start) else {
            return Vec::new();
        };
        let mut visited: FxHashSet<ChangeId> = FxHashSet::default();
        visited.insert(start);
        let mut queue: VecDeque<ChangeId> = root.predecessors.iter().copied().collect();
        let mut result = Vec::new();
        // Both guards must hold: if `get()` returns None the id was trimmed
        // and traversal stops for that branch (no panic, no queue extension).
        while let Some(id) = queue.pop_front() {
            if visited.insert(id)
                && let Some(change) = self.get(id)
            {
                result.push(change);
                queue.extend(change.predecessors.iter().copied());
            }
        }
        result
    }

    /// Return `true` if `ancestor` is a causal ancestor of `descendant`.
    ///
    /// Performs a DFS from `descendant` backwards through the predecessor DAG,
    /// pruning branches whose ids are already smaller than `ancestor.id`
    /// (predecessors always have smaller ids, so they can't lead to `ancestor`).
    /// Short-circuits as soon as `ancestor` is found.
    pub fn is_ancestor_of(&self, ancestor: ChangeId, descendant: ChangeId) -> bool {
        if ancestor.0 >= descendant.0 {
            return false;
        }
        let Some(desc) = self.get(descendant) else {
            return false;
        };
        let mut stack: Vec<ChangeId> = desc
            .predecessors
            .iter()
            .copied()
            .filter(|&pid| pid.0 >= ancestor.0)
            .collect();
        let mut visited: FxHashSet<ChangeId> = FxHashSet::default();
        while let Some(id) = stack.pop() {
            if id == ancestor {
                return true;
            }
            if visited.insert(id)
                && let Some(c) = self.get(id)
            {
                stack.extend(
                    c.predecessors
                        .iter()
                        .copied()
                        .filter(|&pid| pid.0 >= ancestor.0),
                );
            }
        }
        false
    }

    /// Remove all changes with a batch index strictly older than
    /// `retain_from_batch`.
    ///
    /// Before discarding, generates per-locus `TrimSummary` entries that
    /// capture aggregate information (change count, net state delta, kinds)
    /// for the trimmed range. These summaries persist in the log and allow
    /// `causal_coarse_trail` (E2) to provide a "coarse trail" instead of a
    /// dead end when a causal BFS walk hits the trim boundary.
    ///
    /// Returns the number of changes removed. This is a destructive,
    /// irreversible operation — callers should ensure that no live
    /// predecessor references point into the trimmed range. The engine
    /// enforces this by requiring callers to run `trim_change_log` only
    /// after `weather_entities` (which strips predecessor id lists from
    /// compressed layers) or in workloads where old predecessor ids are
    /// never queried.
    pub fn trim_before_batch(&mut self, retain_from_batch: BatchId) -> usize {
        let split = self
            .changes
            .partition_point(|c| c.batch < retain_from_batch);
        if split == 0 {
            return 0;
        }

        // ── E2: generate per-locus summaries before discarding ──────────────
        // Walk only the to-be-trimmed slice to aggregate per-locus stats
        // and populate the trimmed_id_to_locus reverse index.
        {
            let mut locus_stats: FxHashMap<
                LocusId,
                (u32, Vec<f32>, Vec<f32>, Vec<InfluenceKindId>, BatchId),
            > = FxHashMap::default();
            for change in &self.changes[..split] {
                let ChangeSubject::Locus(locus) = change.subject else {
                    continue;
                };
                // Build the trimmed-id reverse index so causal_coarse_trail can
                // resolve trimmed predecessor IDs back to their subject locus.
                self.trimmed_id_to_locus.insert(change.id, locus);
                let entry = locus_stats.entry(locus).or_insert_with(|| {
                    let dim = change
                        .after
                        .as_slice()
                        .len()
                        .max(change.before.as_slice().len());
                    (
                        0,
                        vec![0.0f32; dim],
                        vec![0.0f32; dim],
                        Vec::new(),
                        change.batch,
                    )
                });
                entry.0 += 1;
                // Sum after and before independently; delta = sum_after - sum_before.
                let aft = change.after.as_slice();
                let bef = change.before.as_slice();
                let dim = entry.1.len();
                for i in 0..dim {
                    entry.1[i] += aft.get(i).copied().unwrap_or(0.0);
                    entry.2[i] += bef.get(i).copied().unwrap_or(0.0);
                }
                if !entry.3.contains(&change.kind) {
                    entry.3.push(change.kind);
                }
                // Track earliest batch in the range.
                if change.batch < entry.4 {
                    entry.4 = change.batch;
                }
            }

            for (locus, (count, sum_after, sum_before, kinds, batch_from)) in locus_stats {
                let delta: Vec<f32> = sum_after
                    .iter()
                    .zip(sum_before.iter())
                    .map(|(a, b)| a - b)
                    .collect();
                let summary = TrimSummary {
                    locus,
                    batch_from,
                    batch_to: retain_from_batch,
                    change_count: count,
                    net_delta_state: graph_core::StateVector::from_slice(&delta),
                    kinds_observed: kinds,
                };
                self.summaries.entry(locus).or_default().push(summary);
            }
        }

        if split == self.changes.len() {
            // Trimming the entire log — clear all indices.
            self.by_locus.clear();
            self.by_relationship.clear();
            self.by_batch.clear();
            self.changes.clear();
            return split;
        }
        // The first id we keep; id-indexed vecs are oldest-first so we can
        // use partition_point to strip the front of each vec in O(log k).
        let first_kept = self.changes[split].id;
        for ids in self.by_locus.values_mut() {
            let remove = ids.partition_point(|&id| id < first_kept);
            ids.drain(..remove);
        }
        for ids in self.by_relationship.values_mut() {
            let remove = ids.partition_point(|&id| id < first_kept);
            ids.drain(..remove);
        }
        // Batch entries for fully-trimmed batches are dropped wholesale.
        self.by_batch.retain(|&b, _| b >= retain_from_batch);
        self.changes.drain(..split).count()
    }

    // ── Coarse trail (E2) ────────────────────────────────────────────────────

    /// Return the trim summaries for `locus`, oldest first.
    ///
    /// Empty when `trim_before_batch` has never been called or this locus had
    /// no changes in the trimmed range.
    pub fn trim_summaries_for_locus(&self, locus: LocusId) -> &[TrimSummary] {
        self.summaries.get(&locus).map(Vec::as_slice).unwrap_or(&[])
    }

    /// All trim summaries across all loci, in insertion order per locus.
    pub fn all_trim_summaries(&self) -> impl Iterator<Item = &TrimSummary> {
        self.summaries.values().flat_map(|v| v.iter())
    }

    /// Resolve a trimmed `ChangeId` to the `LocusId` of the change that was
    /// removed — enabling `causal_coarse_trail` to fetch the right `TrimSummary`.
    ///
    /// Returns `None` when the ID was never trimmed (still in the log or
    /// unknown).
    pub fn trimmed_locus_for(&self, id: ChangeId) -> Option<LocusId> {
        self.trimmed_id_to_locus.get(&id).copied()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use graph_core::{InfluenceKindId, StateVector};

    fn change_with_preds(id: u64, locus: u64, batch: u64, preds: Vec<u64>) -> Change {
        Change {
            id: ChangeId(id),
            subject: ChangeSubject::Locus(LocusId(locus)),
            kind: InfluenceKindId(1),
            predecessors: preds.into_iter().map(ChangeId).collect(),
            before: StateVector::empty(),
            after: StateVector::empty(),
            batch: BatchId(batch),
            wall_time: None,
            metadata: None,
        }
    }

    fn change(id: u64, locus: u64, batch: u64) -> Change {
        change_with_preds(id, locus, batch, vec![])
    }

    #[test]
    fn batch_filter() {
        let mut log = ChangeLog::new();
        log.append(change(1, 10, 0));
        log.append(change(2, 11, 0));
        log.append(change(3, 10, 1));
        let in_batch_0: Vec<_> = log.batch(BatchId(0)).map(|c| c.id.0).collect();
        assert_eq!(in_batch_0, vec![1, 2]);
    }

    #[test]
    fn changes_to_locus_returns_newest_first() {
        let mut log = ChangeLog::new();
        log.append(change(1, 10, 0));
        log.append(change(2, 11, 0));
        log.append(change(3, 10, 1));
        let to_10: Vec<_> = log.changes_to_locus(LocusId(10)).map(|c| c.id.0).collect();
        assert_eq!(to_10, vec![3, 1]);
    }

    #[test]
    fn trim_before_batch_removes_older_entries() {
        let mut log = ChangeLog::new();
        log.append(change(1, 10, 0));
        log.append(change(2, 11, 0));
        log.append(change(3, 10, 1));
        log.append(change(4, 11, 2));

        let removed = log.trim_before_batch(BatchId(1));
        assert_eq!(removed, 2, "two entries in batch 0 removed");
        assert_eq!(log.len(), 2);
        let remaining_batches: Vec<u64> = log.iter().map(|c| c.batch.0).collect();
        assert!(remaining_batches.iter().all(|&b| b >= 1));
    }

    #[test]
    fn trim_before_batch_keeps_all_when_retain_is_zero() {
        let mut log = ChangeLog::new();
        log.append(change(1, 10, 0));
        log.append(change(2, 10, 5));
        let removed = log.trim_before_batch(BatchId(0));
        assert_eq!(removed, 0);
        assert_eq!(log.len(), 2);
    }

    #[test]
    fn predecessors_returns_direct_parents() {
        let mut log = ChangeLog::new();
        log.append(change(1, 10, 0));
        log.append(change(2, 11, 0));
        log.append(change_with_preds(3, 10, 1, vec![1, 2]));

        let preds: Vec<u64> = log.predecessors(ChangeId(3)).map(|c| c.id.0).collect();
        assert_eq!(preds, vec![1, 2]);
    }

    #[test]
    fn predecessors_of_stimulus_is_empty() {
        let mut log = ChangeLog::new();
        log.append(change(1, 10, 0));
        assert_eq!(log.predecessors(ChangeId(1)).count(), 0);
    }

    #[test]
    fn causal_ancestors_walks_full_dag() {
        // DAG: 3 → {1, 2}, 4 → {3}, so ancestors of 4 are {3, 1, 2}
        let mut log = ChangeLog::new();
        log.append(change(1, 10, 0));
        log.append(change(2, 11, 0));
        log.append(change_with_preds(3, 10, 1, vec![1, 2]));
        log.append(change_with_preds(4, 10, 2, vec![3]));

        let mut ancestors: Vec<u64> = log
            .causal_ancestors(ChangeId(4))
            .iter()
            .map(|c| c.id.0)
            .collect();
        ancestors.sort_unstable();
        assert_eq!(ancestors, vec![1, 2, 3]);
    }

    #[test]
    fn is_ancestor_of_direct_predecessor() {
        let mut log = ChangeLog::new();
        log.append(change(1, 10, 0));
        log.append(change_with_preds(2, 11, 1, vec![1]));
        assert!(log.is_ancestor_of(ChangeId(1), ChangeId(2)));
        assert!(!log.is_ancestor_of(ChangeId(2), ChangeId(1)));
    }

    #[test]
    fn is_ancestor_of_transitive() {
        // 1 → 2 → 3; is_ancestor_of(1, 3) == true
        let mut log = ChangeLog::new();
        log.append(change(1, 10, 0));
        log.append(change_with_preds(2, 11, 1, vec![1]));
        log.append(change_with_preds(3, 12, 2, vec![2]));
        assert!(log.is_ancestor_of(ChangeId(1), ChangeId(3)));
        assert!(!log.is_ancestor_of(ChangeId(3), ChangeId(1)));
    }

    #[test]
    fn is_ancestor_of_unrelated() {
        let mut log = ChangeLog::new();
        log.append(change(1, 10, 0));
        log.append(change(2, 11, 0));
        assert!(!log.is_ancestor_of(ChangeId(1), ChangeId(2)));
        assert!(!log.is_ancestor_of(ChangeId(2), ChangeId(1)));
    }

    #[test]
    fn causal_ancestors_deduplicates_shared_ancestors() {
        // DAG: 1 → {0}, 2 → {0} (diamond), 3 → {1, 2}; ancestor 0 appears once
        let mut log = ChangeLog::new();
        log.append(change(0, 10, 0));
        log.append(change_with_preds(1, 11, 1, vec![0]));
        log.append(change_with_preds(2, 12, 1, vec![0]));
        log.append(change_with_preds(3, 10, 2, vec![1, 2]));

        let mut ancestors: Vec<u64> = log
            .causal_ancestors(ChangeId(3))
            .iter()
            .map(|c| c.id.0)
            .collect();
        ancestors.sort_unstable();
        assert_eq!(ancestors, vec![0, 1, 2]);
    }

    // ── E2: trim summaries ────────────────────────────────────────────────────

    fn change_with_state(id: u64, locus: u64, batch: u64, before: &[f32], after: &[f32]) -> Change {
        Change {
            id: ChangeId(id),
            subject: ChangeSubject::Locus(LocusId(locus)),
            kind: InfluenceKindId(1),
            predecessors: vec![],
            before: StateVector::from_slice(before),
            after: StateVector::from_slice(after),
            batch: BatchId(batch),
            wall_time: None,
            metadata: None,
        }
    }

    #[test]
    fn trim_generates_summary_for_affected_locus() {
        let mut log = ChangeLog::new();
        // Two changes to locus 10 in batch 0, one in batch 1 (kept after trim).
        log.append(change_with_state(0, 10, 0, &[0.0], &[1.0]));
        log.append(change_with_state(1, 10, 0, &[1.0], &[2.0]));
        log.append(change_with_state(2, 10, 1, &[2.0], &[3.0]));

        log.trim_before_batch(BatchId(1));

        let summaries = log.trim_summaries_for_locus(LocusId(10));
        assert_eq!(summaries.len(), 1);
        let s = &summaries[0];
        assert_eq!(s.locus, LocusId(10));
        assert_eq!(s.batch_from, BatchId(0));
        assert_eq!(s.batch_to, BatchId(1));
        assert_eq!(s.change_count, 2);
        // net_delta = (1.0 - 0.0) + (2.0 - 1.0) = 2.0
        assert!((s.net_delta_state.as_slice()[0] - 2.0).abs() < 1e-5);
    }

    #[test]
    fn trim_summary_tracks_kinds_observed() {
        let mut log = ChangeLog::new();
        log.append(Change {
            id: ChangeId(0),
            subject: ChangeSubject::Locus(LocusId(1)),
            kind: InfluenceKindId(2),
            predecessors: vec![],
            before: StateVector::from_slice(&[0.0]),
            after: StateVector::from_slice(&[1.0]),
            batch: BatchId(0),
            wall_time: None,
            metadata: None,
        });
        log.append(Change {
            id: ChangeId(1),
            subject: ChangeSubject::Locus(LocusId(1)),
            kind: InfluenceKindId(5),
            predecessors: vec![],
            before: StateVector::from_slice(&[1.0]),
            after: StateVector::from_slice(&[2.0]),
            batch: BatchId(0),
            wall_time: None,
            metadata: None,
        });
        log.append(change(2, 1, 1));

        log.trim_before_batch(BatchId(1));

        let s = &log.trim_summaries_for_locus(LocusId(1))[0];
        let mut kinds = s.kinds_observed.clone();
        kinds.sort();
        assert!(kinds.contains(&InfluenceKindId(2)));
        assert!(kinds.contains(&InfluenceKindId(5)));
    }

    #[test]
    fn trim_summary_not_generated_when_nothing_trimmed() {
        let mut log = ChangeLog::new();
        log.append(change(0, 10, 5));
        // retain_from >= all batches → nothing removed
        log.trim_before_batch(BatchId(3));
        assert!(log.trim_summaries_for_locus(LocusId(10)).is_empty());
    }

    #[test]
    fn multiple_trims_accumulate_summaries() {
        let mut log = ChangeLog::new();
        for i in 0u64..6 {
            log.append(change_with_state(i, 10, i, &[i as f32], &[i as f32 + 1.0]));
        }

        log.trim_before_batch(BatchId(2));
        log.trim_before_batch(BatchId(4));

        // Two trim calls → two summaries for locus 10.
        let summaries = log.trim_summaries_for_locus(LocusId(10));
        assert_eq!(summaries.len(), 2);
        assert_eq!(summaries[0].batch_from, BatchId(0));
        assert_eq!(summaries[0].batch_to, BatchId(2));
        assert_eq!(summaries[1].batch_from, BatchId(2));
        assert_eq!(summaries[1].batch_to, BatchId(4));
    }
}
